# Generated by Django 5.1.4 on 2025-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(help_text='Video title.', max_length=1000),
        ),
    ]
