# Generated by Django 5.1.4 on 2025-01-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_youtubevideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
