# Generated by Django 5.1.4 on 2025-01-16 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_youtubevideo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(help_text='Duration of the video in seconds (e.g., 9000s to 10800s).', validators=[django.core.validators.MinValueValidator(7200), django.core.validators.MaxValueValidator(10800)]),
        ),
    ]
