# Generated by Django 5.1.4 on 2025-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_youtubevideo_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
