# Generated by Django 5.1.4 on 2025-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_youtubevideo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(help_text='Duration of the video in seconds (e.g., 9000s to 10800s).'),
        ),
    ]
